services:

  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 120s docker-entrypoint.sh
    command: node index.js
    networks:
      - node-network
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
      - db

  nginx:
    build:
      context: nginx
    container_name: nginx
    tty: true
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on: 
      - app  


  db:
    platform: linux/x86_64
    build:
      context: mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/mysql_files:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge